// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2m7BPn2LP575mFFxAIr9Akxi78xADeDY',
    appId: '1:693913873044:web:e9793d961e06ea2b942281',
    messagingSenderId: '693913873044',
    projectId: 'restaurant-app-2e4de',
    authDomain: 'restaurant-app-2e4de.firebaseapp.com',
    storageBucket: 'restaurant-app-2e4de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7yx4GOocrL0LpdEkfZHef2xwCdYRnh0c',
    appId: '1:693913873044:android:44b7674481d42cb5942281',
    messagingSenderId: '693913873044',
    projectId: 'restaurant-app-2e4de',
    storageBucket: 'restaurant-app-2e4de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG7daJB00kjVCvk-chCJRV7ZK9YWqzsz0',
    appId: '1:693913873044:ios:0c775064d432a6f3942281',
    messagingSenderId: '693913873044',
    projectId: 'restaurant-app-2e4de',
    storageBucket: 'restaurant-app-2e4de.firebasestorage.app',
    iosBundleId: 'com.example.restaurantFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG7daJB00kjVCvk-chCJRV7ZK9YWqzsz0',
    appId: '1:693913873044:ios:0c775064d432a6f3942281',
    messagingSenderId: '693913873044',
    projectId: 'restaurant-app-2e4de',
    storageBucket: 'restaurant-app-2e4de.firebasestorage.app',
    iosBundleId: 'com.example.restaurantFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2m7BPn2LP575mFFxAIr9Akxi78xADeDY',
    appId: '1:693913873044:web:40db6865e4633139942281',
    messagingSenderId: '693913873044',
    projectId: 'restaurant-app-2e4de',
    authDomain: 'restaurant-app-2e4de.firebaseapp.com',
    storageBucket: 'restaurant-app-2e4de.firebasestorage.app',
  );
}
